# $FreeBSD: head/usr.sbin/bsdconfig/include/Makefile 274073 2014-11-04 00:14:38Z dteske $

NO_OBJ=

FILESDIR=	${LIBEXECDIR}/bsdconfig/include
FILES=		bsdconfig.hlp media.hlp messages.subr network_device.hlp \
		options.hlp tcp.hlp usage.hlp

.include <bsd.prog.mk>
