# $FreeBSD: head/lib/clang/liblldbPluginPlatformFreeBSD/Makefile 276479 2014-12-31 20:31:32Z dim $

.include <bsd.own.mk>

LIB=	lldbPluginPlatformFreeBSD

SRCDIR=	tools/lldb/source/Plugins/Platform/FreeBSD
SRCS=	PlatformFreeBSD.cpp

TGHDRS=	AttrList \
	Attrs \
	DiagnosticCommonKinds \
	DeclNodes \
	StmtNodes \
	CommentCommandList

.include "../lldb.lib.mk"
