# $FreeBSD: head/usr.sbin/bsdconfig/includes/Makefile 274073 2014-11-04 00:14:38Z dteske $

NO_OBJ=

SUBDIR= include

FILESDIR=	${LIBEXECDIR}/bsdconfig/includes
FILES=		INDEX USAGE

SCRIPTSDIR=	${FILESDIR}
SCRIPTS=	includes

.include <bsd.prog.mk>
