# $FreeBSD: head/usr.sbin/ancontrol/Makefile 275054 2014-11-25 16:57:27Z bapt $

PROG=	ancontrol
MAN=	ancontrol.8

WARNS?=	3
CFLAGS+= -DANCACHE -I${.CURDIR}/../../sys

LIBADD=	md

.include <bsd.prog.mk>
