# $FreeBSD: head/sys/modules/rtwn/Makefile 293017 2015-12-31 23:48:07Z adrian $

.PATH:  ${.CURDIR}/../../dev/rtwn

KMOD    = if_rtwn
SRCS    = if_rtwn.c device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
