# ex:ts=8
#
# Makefile for amd
# 	This file is under a "BSD" copyright (c) by David O'Brien 1998
#
# $FreeBSD: head/usr.sbin/amd/wire-test/Makefile 267233 2014-06-08 17:29:31Z bdrewery $

.PATH: ${.CURDIR}/../../../contrib/amd/wire-test

PROG=	wire-test
MAN=	wire-test.8

DPADD=	${LIBAMU}
LDADD=	${LIBAMU}

NO_PIE=	yes

.include <bsd.prog.mk>
