# $FreeBSD: head/sys/modules/wlan_tkip/Makefile 269540 2014-08-04 22:37:02Z imp $

.PATH: ${.CURDIR}/../../net80211

KMOD=	wlan_tkip
SRCS=	ieee80211_crypto_tkip.c
SRCS+=	opt_wlan.h

.include <bsd.kmod.mk>
