# $FreeBSD: head/usr.bin/mkesdb/Makefile 284945 2015-06-30 06:02:42Z jhibbits $

.PATH: ${.CURDIR}/../../lib/libc/iconv

PROG=	mkesdb

NO_WMISSING_VARIABLE_DECLARATIONS=

.include "${.CURDIR}/Makefile.inc"
.include <bsd.prog.mk>
