# $FreeBSD: head/usr.sbin/zonectl/Makefile 300207 2016-05-19 14:08:36Z ken $

PROG=	zonectl
SRCS=	zonectl.c
SDIR=	${.CURDIR}/../../sys
LIBADD= cam sbuf util
MAN=	zonectl.8
CFLAGS+=-g -O0

.include <bsd.prog.mk>
