# $FreeBSD: head/usr.sbin/bsdconfig/networking/Makefile 291347 2015-11-26 01:14:27Z bdrewery $

SUBDIR= include share

FILESDIR=	${LIBEXECDIR}/bsdconfig/120.networking
FILES=		INDEX USAGE

SCRIPTSDIR=	${FILESDIR}
SCRIPTS=	defaultrouter devices hostname nameservers networking

.include <bsd.prog.mk>
