# $FreeBSD: head/usr.sbin/bsdconfig/networking/Makefile 274073 2014-11-04 00:14:38Z dteske $

NO_OBJ=

SUBDIR= include share

FILESDIR=	${LIBEXECDIR}/bsdconfig/120.networking
FILES=		INDEX USAGE

SCRIPTSDIR=	${FILESDIR}
SCRIPTS=	defaultrouter devices hostname nameservers networking

.include <bsd.prog.mk>
