#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: head/usr.bin/vgrind/RETEST/Makefile 264400 2014-04-13 05:21:56Z imp $

PROG=	retest
SRCS=	regexp.c retest.c
.PATH:	${.CURDIR}/..
MAN=

install:

.include <bsd.prog.mk>
