# $FreeBSD: head/lib/clang/libclangformat/Makefile 301993 2016-06-17 16:46:58Z bdrewery $

.include <bsd.own.mk>

LIB=	clangformat

SRCDIR=	tools/clang/lib/Format

SRCS=	BreakableToken.cpp \
	ContinuationIndenter.cpp \
	Format.cpp \
	FormatToken.cpp \
	TokenAnnotator.cpp \
	UnwrappedLineFormatter.cpp \
	UnwrappedLineParser.cpp \
	WhitespaceManager.cpp

TGHDRS=	DiagnosticCommonKinds

.include "../clang.lib.mk"
