# $FreeBSD: head/usr.bin/svn/lib/Makefile 274885 2014-11-22 19:44:49Z bapt $

SUBDIR=	libapr libapr_util libserf \
	libsvn_client libsvn_delta libsvn_diff libsvn_fs libsvn_fs_fs \
	libsvn_fs_util libsvn_ra libsvn_ra_local libsvn_ra_serf \
	libsvn_ra_svn libsvn_repos libsvn_subr libsvn_wc

.include <bsd.subdir.mk>
