# $FreeBSD: head/sys/modules/if_bridge/Makefile 269540 2014-08-04 22:37:02Z imp $

.PATH:	${.CURDIR}/../../net
KMOD=	if_bridge
SRCS=	if_bridge.c opt_inet.h opt_inet6.h opt_carp.h

.include <bsd.kmod.mk>
