# $FreeBSD: head/usr.bin/make/tests/sysmk/t2/mk/Makefile 263348 2014-03-19 12:32:50Z jmmv $

TESTSDIR=	${TESTSBASE}/usr.bin/make/sysmk/t2/mk

FILESDIR=		${TESTSDIR}
FILES=			sys.mk.test
FILESNAME_sys.mk.test=	sys.mk

.include <bsd.test.mk>
