# $FreeBSD: head/usr.sbin/bsdinstall/scripts/Makefile 264400 2014-04-13 05:21:56Z imp $

SCRIPTS= auto adduser checksum config docsinstall entropy hostname jail \
	 keymap mirrorselect mount netconfig netconfig_ipv4 netconfig_ipv6 \
	 rootpass script services time umount wlanconfig zfsboot
BINDIR= /usr/libexec/bsdinstall

MAN=

.include <bsd.prog.mk>
