# $FreeBSD: head/gnu/usr.bin/texinfo/install-info/Makefile 270168 2014-08-19 15:04:32Z bdrewery $

PROG=	install-info

DPADD=	${LIBTXI}
LDADD=	${LIBTXI}

.include <bsd.prog.mk>

.PATH:	${TXIDIR}/util ${TXIDIR}/doc
