# $FreeBSD: head/gnu/usr.bin/texinfo/install-info/Makefile 267233 2014-06-08 17:29:31Z bdrewery $

PROG=	install-info

DPADD=	${LIBTXI}
LDADD=	${LIBTXI}

NO_PIE=	yes

.include <bsd.prog.mk>

.PATH:	${TXIDIR}/util ${TXIDIR}/doc
