# $FreeBSD: head/usr.bin/make/tests/syntax/Makefile 263348 2014-03-19 12:32:50Z jmmv $

TESTSDIR=	${TESTSBASE}/usr.bin/make/syntax

TESTS_SUBDIRS=	directive-t0 enl funny-targets semi

.include <bsd.test.mk>
