# $FreeBSD: head/usr.bin/make/tests/variables/Makefile 263348 2014-03-19 12:32:50Z jmmv $

TESTSDIR=	${TESTSBASE}/usr.bin/make/variables

TESTS_SUBDIRS=	modifier_M modifier_t opt_V t0

.include <bsd.test.mk>
