# $FreeBSD: head/share/examples/smbfs/print/Makefile 291347 2015-11-26 01:14:27Z bdrewery $

FILESDIR= ${SHAREDIR}/examples/smbfs/print
FILES=	lj6l ljspool printcap.sample tolj

.PATH: ${.CURDIR}/../../../../contrib/smbfs/examples/print

.include <bsd.prog.mk>
