# $FreeBSD: head/share/doc/legal/intel_iwn/Makefile 284321 2015-06-12 14:30:27Z sjg $

FILES=		${.CURDIR}/../../../../sys/contrib/dev/iwn/LICENSE
FILESDIR=	${SHAREDIR}/doc/legal/intel_iwn

.include <bsd.prog.mk>
