# $FreeBSD: head/lib/libc/tests/db/Makefile 274075 2014-11-04 00:56:25Z ngie $

TESTSDIR=	${TESTSBASE}/lib/libc/db

BINDIR=		${TESTSDIR}

PROGS=		h_db

FILESDIR=	${TESTSDIR}

FILES=		README

NETBSD_ATF_TESTS_SH+=	db_test

.include "../Makefile.netbsd-tests"

.include <bsd.test.mk>
