# $FreeBSD: head/lib/clang/libllvmmipsinfo/Makefile 296417 2016-03-05 20:24:31Z dim $

.include <bsd.own.mk>

LIB=	llvmmipsinfo

SRCDIR=	lib/Target/Mips/TargetInfo
INCDIR=	lib/Target/Mips
SRCS=	MipsTargetInfo.cpp

TGHDRS=	Attributes \
	MipsGenInstrInfo \
	MipsGenRegisterInfo \
	MipsGenSubtargetInfo

.include "../clang.lib.mk"
