#	$FreeBSD: head/sbin/ipf/ipresend/Makefile 298107 2016-04-16 07:45:30Z gjb $

PACKAGE=	ipf
PROG=		ipresend
SRCS=		ipresend.c ip.c resend.c sbpf.c sock.c 44arp.c
MAN=		ipresend.1

.PATH:		${.CURDIR}/../../../contrib/ipfilter/ipsend

.include <bsd.prog.mk>
