# $FreeBSD: head/lib/libcasper/services/Makefile 296125 2016-02-26 22:14:04Z bdrewery $

SUBDIR=		cap_dns
SUBDIR+=	cap_grp
SUBDIR+=	cap_pwd
SUBDIR+=	cap_random
SUBDIR+=	cap_sysctl

SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
