# $FreeBSD: head/sys/boot/i386/zfsloader/Makefile 264400 2014-04-13 05:21:56Z imp $

.PATH:	${.CURDIR}/../loader

LOADER=		zfsloader
NEWVERSWHAT=	"ZFS enabled bootstrap loader" x86
LOADER_ZFS_SUPPORT=yes
LOADER_ONLY=	yes
MAN=

.include "${.CURDIR}/../loader/Makefile"

