# $FreeBSD: head/sys/dev/patm/genrtab/Makefile 264400 2014-04-13 05:21:56Z imp $
#
# This program is used to generate the if_patm_rtables.c file
# for the idt77252 driver. It is not installed.
#
PROG=	genrtab
INTERNALPROG=
WARNS?=	5
MAN=
DPADD=	${LIBM}
LDADD=	-lm

.include <bsd.prog.mk>
