# $FreeBSD: head/lib/clang/liblldbPluginExpressionParserGo/Makefile 293124 2016-01-04 00:02:58Z emaste $

.include <bsd.own.mk>

LIB=	lldbPluginExpressionParserGo

SRCDIR=	tools/lldb/source/Plugins/ExpressionParser/Go
SRCS=	GoLexer.cpp \
	GoParser.cpp \
	GoUserExpression.cpp

.include "../lldb.lib.mk"
