# $FreeBSD: head/usr.sbin/bsdconfig/usermgmt/include/Makefile 274073 2014-11-04 00:14:38Z dteske $

NO_OBJ=

FILESDIR=	${LIBEXECDIR}/bsdconfig/070.usermgmt/include
FILES=		messages.subr usermgmt.hlp

.include <bsd.prog.mk>
