# $FreeBSD: head/lib/atf/tests/Makefile 289172 2015-10-12 08:16:03Z ngie $

.include <bsd.own.mk>

TESTSDIR=	${TESTSBASE}/lib/atf

.PATH:		${SRCTOP}/tests
KYUAFILE=	yes

SUBDIR=		test-programs

.include <bsd.test.mk>
