# $FreeBSD: head/usr.sbin/bsdconfig/startup/Makefile 274073 2014-11-04 00:14:38Z dteske $

NO_OBJ=

SUBDIR= include share

FILESDIR=	${LIBEXECDIR}/bsdconfig/140.startup
FILES=		INDEX USAGE

SCRIPTSDIR=	${FILESDIR}
SCRIPTS=	misc rcadd rcconf rcdelete rcedit rcvar startup

.include <bsd.prog.mk>
