# $FreeBSD: head/lib/clang/libllvmaarch64utils/Makefile 276783 2015-01-07 19:06:27Z dim $

.include <bsd.own.mk>

LIB=	llvmaarch64utils

SRCDIR=	lib/Target/AArch64/Utils
INCDIR=	lib/Target/AArch64
SRCS=	AArch64BaseInfo.cpp

TGHDRS=	AArch64GenInstrInfo \
	AArch64GenRegisterInfo \
	AArch64GenSubtargetInfo

.include "../clang.lib.mk"
