# $FreeBSD: head/usr.bin/cut/tests/Makefile 289172 2015-10-12 08:16:03Z ngie $

.include <bsd.own.mk>

NETBSD_ATF_TESTS_SH=	cut_test

FILESDIR=	${TESTSDIR}
FILES=		d_basic.out
FILES+=		d_cut.in
FILES+=		d_dflag.out
FILES+=		d_dsflag.out
FILES+=		d_latin1.in
FILES+=		d_sflag.out
FILES+=		d_utf8.in

.include <netbsd-tests.test.mk>

.include <bsd.test.mk>
