# $FreeBSD: head/usr.bin/cut/tests/Makefile 299094 2016-05-04 23:20:53Z ngie $

PACKAGE=	tests

NETBSD_ATF_TESTS_SH=	cut_test

${PACKAGE}FILES=		d_basic.out
${PACKAGE}FILES+=		d_cut.in
${PACKAGE}FILES+=		d_dflag.out
${PACKAGE}FILES+=		d_dsflag.out
${PACKAGE}FILES+=		d_latin1.in
${PACKAGE}FILES+=		d_sflag.out
${PACKAGE}FILES+=		d_utf8.in

.include <netbsd-tests.test.mk>

.include <bsd.test.mk>
