# $FreeBSD: head/usr.sbin/bsdconfig/startup/share/Makefile 274073 2014-11-04 00:14:38Z dteske $

NO_OBJ=

FILESDIR=	${SHAREDIR}/bsdconfig/startup
FILES=		rcconf.subr rcedit.subr rcvar.subr

.include <bsd.prog.mk>
