# $FreeBSD: head/share/doc/legal/intel_iwi/Makefile 284321 2015-06-12 14:30:27Z sjg $

FILES=		${.CURDIR}/../../../../sys/contrib/dev/iwi/LICENSE
FILESDIR=	${SHAREDIR}/doc/legal/intel_iwi

.include <bsd.prog.mk>
