# $FreeBSD: head/lib/clang/liblldbHostPOSIX/Makefile 296417 2016-03-05 20:24:31Z dim $

.include <bsd.own.mk>

LIB=	lldbHostPOSIX

SRCDIR=	tools/lldb/source/Host/posix
SRCS=	ConnectionFileDescriptorPosix.cpp \
	DomainSocket.cpp \
	FileSystem.cpp \
	HostInfoPosix.cpp \
	HostProcessPosix.cpp \
	HostThreadPosix.cpp \
	LockFilePosix.cpp \
	PipePosix.cpp \
	ProcessLauncherPosix.cpp

.include "../lldb.lib.mk"
