# $FreeBSD: head/lib/clang/liblldbHostPOSIX/Makefile 288943 2015-10-06 17:53:29Z dim $

.include <bsd.own.mk>

LIB=	lldbHostPOSIX

SRCDIR=	tools/lldb/source/Host/posix
SRCS=	ConnectionFileDescriptorPosix.cpp \
	FileSystem.cpp \
	HostInfoPosix.cpp \
	HostProcessPosix.cpp \
	HostThreadPosix.cpp \
	LockFilePosix.cpp \
	PipePosix.cpp \
	ProcessLauncherPosix.cpp

.include "../lldb.lib.mk"
