# $FreeBSD: head/lib/clang/liblldbHostPOSIX/Makefile 280031 2015-03-15 13:31:13Z dim $

.include <bsd.own.mk>

LIB=	lldbHostPOSIX

SRCDIR=	tools/lldb/source/Host/posix
SRCS=	ConnectionFileDescriptorPosix.cpp \
	FileSystem.cpp \
	HostInfoPosix.cpp \
	HostProcessPosix.cpp \
	HostThreadPosix.cpp \
	PipePosix.cpp \
	ProcessLauncherPosix.cpp

.include "../lldb.lib.mk"
