# $FreeBSD: head/sys/modules/wpi/Makefile 278365 2015-02-07 23:09:03Z adrian $

.PATH:  ${.CURDIR}/../../dev/wpi

KMOD    = if_wpi
SRCS    = if_wpi.c device_if.h bus_if.h pci_if.h opt_wpi.h opt_wlan.h

.include <bsd.kmod.mk>
