# $FreeBSD: head/lib/clang/libllvmlibdriver/Makefile 284735 2015-06-23 18:46:29Z dim $

.include <bsd.own.mk>

LIB=	llvmlibdriver

SRCDIR=	lib/LibDriver
SRCS=	LibDriver.cpp
CFLAGS+= -I${.CURDIR}

TGHDRS=	Options

.include "../clang.lib.mk"
