# $FreeBSD: head/lib/clang/liblldbPluginPlatformGDB/Makefile 276479 2014-12-31 20:31:32Z dim $

.include <bsd.own.mk>

LIB=	lldbPluginPlatformGDB

SRCDIR=	tools/lldb/source/Plugins/Platform/gdb-server
SRCS=	PlatformRemoteGDBServer.cpp

TGHDRS=	AttrList \
	Attrs \
	DiagnosticCommonKinds \
	DeclNodes \
	StmtNodes \
	CommentCommandList

.include "../lldb.lib.mk"
