# From:	@(#)Makefile	8.1 (Berkeley) 6/4/93
# $FreeBSD: head/libexec/rshd/Makefile 275077 2014-11-25 21:18:18Z bapt $

PROG=	rshd
MAN=	rshd.8

WARNS?=	3
WFORMAT=0

LIBADD=	util pam

.include <bsd.prog.mk>
