# $FreeBSD: head/etc/tests/Makefile 277627 2015-01-24 00:37:41Z will $

.include <bsd.own.mk>

TESTSDIR=	${TESTSBASE}/etc

.PATH:		${.CURDIR:H:H}/tests
KYUAFILE=	yes

TESTS_SUBDIRS+=	rc.d

.include <bsd.test.mk>
