# $FreeBSD: head/lib/clang/libllvmlinker/Makefile 296417 2016-03-05 20:24:31Z dim $

.include <bsd.own.mk>

LIB=	llvmlinker

SRCDIR=	lib/Linker
SRCS=	IRMover.cpp \
	LinkModules.cpp

TGHDRS=	Attributes

.include "../clang.lib.mk"
