# $FreeBSD: head/lib/clang/liblldbPluginObjectFileJIT/Makefile 275132 2014-11-26 17:40:03Z emaste $

.include <bsd.own.mk>

LIB=	lldbPluginObjectFileJIT

SRCDIR=	tools/lldb/source/Plugins/ObjectFile/JIT
SRCS=	ObjectFileJIT.cpp

TGHDRS=	AttrList \
	Attrs \
	DiagnosticCommonKinds \
	DeclNodes \
	StmtNodes \
	CommentCommandList

.include "../lldb.lib.mk"
