# $FreeBSD: head/libexec/hyperv/Makefile 291348 2015-11-26 01:14:40Z bdrewery $

.PATH:		${.CURDIR}/../../contrib/hyperv/tools/scripts

BINDIR=		${LIBEXECDIR}/hyperv

SCRIPTS=	hv_set_ifconfig hv_get_dns_info hv_get_dhcp_info

.include <bsd.prog.mk>
