# $FreeBSD: head/libexec/hyperv/Makefile 271493 2014-09-13 02:15:31Z delphij $

.PATH:		${.CURDIR}/../../contrib/hyperv/tools/scripts

BINDIR=		/usr/libexec/hyperv

SCRIPTS=	hv_set_ifconfig hv_get_dns_info hv_get_dhcp_info
NO_OBJ=

.include <bsd.prog.mk>
