# $FreeBSD: head/sys/modules/geom/geom_part/geom_part_ebr/Makefile 285068 2015-07-03 01:50:26Z imp $

.PATH: ${.CURDIR}/../../../../geom/part

KMOD=	geom_part_ebr
SRCS=	g_part_ebr.c

SRCS+=	bus_if.h device_if.h g_part_if.h
SRCS+=	opt_geom.h

.include <bsd.kmod.mk>
