# $FreeBSD: head/usr.bin/make/tests/sysmk/t1/2/1/Makefile 263348 2014-03-19 12:32:50Z jmmv $

TESTSDIR=	${TESTSBASE}/usr.bin/make/sysmk/t1/2/1

TAP_TESTS_SH=	legacy_test

FILESDIR=	${TESTSDIR}
FILES=		cleanup
FILES+=		expected.status.1
FILES+=		expected.stderr.1
FILES+=		expected.stdout.1

.include <bsd.test.mk>
