#
# This builds network tools.
#
# $FreeBSD: head/tools/bsdbox/Makefile.net 263140 2014-03-14 02:58:48Z glebius $
#

CRUNCH_PROGS_sbin+=	route ping
CRUNCH_PROGS_usr.sbin+=	arp

# inetd
CRUNCH_PROGS_usr.sbin+=	inetd
CRUNCH_LIBS+=	-lwrap

#.if ${MK_INET6_SUPPORT} != "no"
#CRUNCH_PROGS_sbin+= ping6
#.endif

# netstat
CRUNCH_PROGS_usr.bin+=	netstat
CRUNCH_LIBS+=	-lmemstat -lnetgraph

# ifconfig
CRUNCH_PROGS_sbin+=	ifconfig

# wlan stuff
CRUNCH_PROGS_usr.sbin+=	wlandebug

# tcpdump
CRUNCH_PROGS_usr.sbin+=	tcpdump
# CRUNCH_LIBS+=	-lpcap -lcrypto
