# $FreeBSD: head/share/examples/pf/Makefile 284255 2015-06-11 04:22:17Z sjg $

FILES=	faq-example1 faq-example2 faq-example3 \
	ackpri queue1 queue2 queue3 queue4 \
	pf.conf \
	spamd

FILESDIR=	${SHAREDIR}/examples/pf

.include <bsd.prog.mk>
