# $FreeBSD: head/libexec/rtld-elf/tests/Makefile 295683 2016-02-17 00:30:28Z bdrewery $

.include <bsd.own.mk>

SUBDIR+=	libpythagoras target

SUBDIR_DEPEND_target=	libpythagoras
ATF_TESTS_C=	ld_library_pathfds

.include <bsd.test.mk>
