# $FreeBSD: head/libexec/rtld-elf/tests/Makefile 269599 2014-08-05 18:05:31Z ngie $

.include <bsd.own.mk>

TESTSDIR=	${TESTSBASE}/libexec/rtld-elf
SUBDIR+=	libpythagoras target

ATF_TESTS_C=	ld_library_pathfds

.include <bsd.test.mk>
