# $FreeBSD: head/lib/libiconv_modules/iconv_std/Makefile 260334 2014-01-05 21:03:49Z dim $

SHLIB=	iconv_std
SRCS+=	citrus_iconv_std.c
CFLAGS.gcc+= --param max-inline-insns-single=32

.include <bsd.lib.mk>
