# $FreeBSD: head/tools/tools/cxgbetool/Makefile 264400 2014-04-13 05:21:56Z imp $

PROG=	cxgbetool
SRCS=	cxgbetool.c
MAN=
CFLAGS+= -I${.CURDIR}/../../../sys/dev/cxgbe -I${.CURDIR}/../../../sys -I.
BINDIR?= /usr/sbin

.include <bsd.prog.mk>
