# $FreeBSD: head/sbin/mdconfig/tests/Makefile 275170 2014-11-27 06:04:00Z ngie $

TESTSDIR=	${TESTSBASE}/sbin/mdconfig

ATF_TESTS_SH=	mdconfig_test


TEST_METADATA.mdconfig_test+=	required_user="root"

.include <bsd.test.mk>
