# $FreeBSD: head/sys/modules/ipdivert/Makefile 269540 2014-08-04 22:37:02Z imp $

.PATH: ${.CURDIR}/../../netinet

KMOD=   ipdivert
SRCS=   ip_divert.c opt_inet.h opt_inet6.h opt_sctp.h

.include <bsd.kmod.mk>
