# $FreeBSD: head/sys/modules/ip6_mroute_mod/Makefile 269540 2014-08-04 22:37:02Z imp $

.PATH: ${.CURDIR}/../../netinet6

KMOD=	ip6_mroute

SRCS=	ip6_mroute.c
SRCS+=	opt_inet6.h opt_mrouting.h

.include <bsd.kmod.mk>
