#!/bin/sh
#
# $FreeBSD: head/etc/rc.d/automountd 270096 2014-08-17 09:44:42Z trasz $
#

# PROVIDE: automountd
# REQUIRE: automount
# KEYWORD: nojail

. /etc/rc.subr

name="automountd"
rcvar="autofs_enable"
pidfile="/var/run/${name}.pid"
command="/usr/sbin/${name}"
required_modules="autofs"

load_rc_config $name
run_rc_command "$1"
