#!/bin/sh
#
# $FreeBSD: head/etc/rc.d/automount 270096 2014-08-17 09:44:42Z trasz $
#

# PROVIDE: automount
# REQUIRE: nfsclient
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="automount"
rcvar="autofs_enable"
start_cmd="automount_start"
stop_cmd="automount_stop"
required_modules="autofs"

automount_start()
{

	/usr/sbin/automount
}

automount_stop()
{

	/sbin/umount -At autofs
}

load_rc_config $name
run_rc_command "$1"
