#!/bin/sh
#
# $FreeBSD: head/etc/rc.d/autounmountd 270096 2014-08-17 09:44:42Z trasz $
#

# PROVIDE: autounmountd
# REQUIRE: nfsclient
# KEYWORD: nojail

. /etc/rc.subr

name="autounmountd"
rcvar="autofs_enable"
pidfile="/var/run/${name}.pid"
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
