#!/bin/sh
#
# $FreeBSD: head/etc/rc.d/automountd 287951 2015-09-18 06:54:52Z trasz $
#

# PROVIDE: automountd
# REQUIRE: DAEMON
# KEYWORD: nojail

. /etc/rc.subr

name="automountd"
rcvar="autofs_enable"
pidfile="/var/run/${name}.pid"
command="/usr/sbin/${name}"
required_modules="autofs"

load_rc_config $name
run_rc_command "$1"
