#!/bin/sh
#
# $FreeBSD: head/etc/rc.d/gssd 270780 2014-08-29 06:23:00Z hrs $
#

# PROVIDE: gssd
# REQUIRE: root
# KEYWORD: nojail shutdown

. /etc/rc.subr

name=gssd
rcvar=gssd_enable

load_rc_config $name
run_rc_command "$1"
