#!/bin/sh
#
# $FreeBSD: head/etc/rc.d/NETWORKING 292752 2015-12-26 18:21:32Z ian $
#

# PROVIDE: NETWORKING NETWORK
# REQUIRE: netif netwait netoptions routing ppp ipfw stf
# REQUIRE: defaultroute routed route6d mroute6d resolv bridge
# REQUIRE: static_arp static_ndp

#	This is a dummy dependency, for services which require networking
#	to be operational before starting.
