#!/bin/sh
#
# $FreeBSD: head/etc/rc.d/NETWORKING 278704 2015-02-13 20:49:43Z ngie $
#

# PROVIDE: NETWORKING NETWORK
# REQUIRE: netif netoptions routing ppp ipfw stf
# REQUIRE: defaultroute routed route6d mroute6d resolv bridge
# REQUIRE: static_arp static_ndp

#	This is a dummy dependency, for services which require networking
#	to be operational before starting.
