#!/bin/sh
#
# $FreeBSD: head/etc/rc.d/rctl 261931 2014-02-15 14:50:47Z bdrewery $
#

# PROVIDE: rctl
# BEFORE: LOGIN
# KEYWORD: nojail

. /etc/rc.subr

name="rctl"
start_cmd="rctl_start"
stop_cmd="rctl_stop"

rctl_start()
{
	if [ -f ${rctl_rules} ]; then
		while read var comments
		do
			case ${var} in
			\#*|'')
				;;
			*)
				rctl -a "${var}"
				;;
			esac
		done < ${rctl_rules}
	fi
}

rctl_stop()
{

	rctl -r :
}

load_rc_config $name
run_rc_command "$1"
