#!/bin/sh
#
# $FreeBSD: head/etc/rc.d/SERVERS 270782 2014-08-29 07:51:47Z hrs $
#

# PROVIDE: SERVERS
# REQUIRE: mountcritremote abi ldconfig savecore watchdogd kdc

#	This is a dummy dependency, for early-start servers relying on
#	some basic configuration.
