#!/bin/sh
#
# $FreeBSD: head/etc/rc.d/utx 278706 2015-02-13 20:52:23Z ngie $
#

# PROVIDE: utx
# REQUIRE: DAEMON FILESYSTEMS
# BEFORE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="utx"
start_cmd="utx boot"
stop_cmd="utx shutdown"

load_rc_config $name
run_rc_command "$1"
