# $FreeBSD: head/sys/modules/siftr/Makefile 269538 2014-08-04 22:34:12Z imp $

.PATH:  ${.CURDIR}/../../netinet
KMOD=	siftr
SRCS=	siftr.c

# Uncomment to add IPv6 support
#CFLAGS+=-DSIFTR_IPV6

.include <bsd.kmod.mk>
