#	@(#)Makefile	8.4 (Berkeley) 6/22/95
#
# $FreeBSD: head/sbin/umount/Makefile 298107 2016-04-16 07:45:30Z gjb $

PACKAGE=runtime
PROG=	umount
SRCS=	umount.c vfslist.c mounttab.c
MAN=	umount.8

MOUNT=	${.CURDIR}/../mount
UMNTALL= ${.CURDIR}/../../usr.sbin/rpc.umntall
CFLAGS+= -I${MOUNT} -I${UMNTALL}

.PATH: ${MOUNT} ${UMNTALL}

.include <bsd.prog.mk>
