# $FreeBSD: head/lib/clang/libllvmpasses/Makefile 283770 2015-05-30 15:39:49Z dim $

.include <src.opts.mk>

LIB=	llvmpasses

SRCDIR=	lib/Passes
SRCS=	PassBuilder.cpp

TGHDRS=	Intrinsics

.include "../clang.lib.mk"
