# $FreeBSD: head/lib/clang/libllvmpasses/Makefile 296417 2016-03-05 20:24:31Z dim $

.include <src.opts.mk>

LIB=	llvmpasses

SRCDIR=	lib/Passes
SRCS=	PassBuilder.cpp

TGHDRS=	Attributes \
	Intrinsics

.include "../clang.lib.mk"
