# $FreeBSD: head/libexec/rtld-elf/tests/libpythagoras/Makefile 291738 2015-12-04 03:17:47Z bdrewery $

.include <bsd.own.mk>

LIB=		pythagoras
SHLIB_MAJOR=	0

LIBDIR=		${TESTSBASE}/libexec/rtld-elf
SHLIBDIR=	${TESTSBASE}/libexec/rtld-elf

SRCS=		pythagoras.c

LIBADD=		m

.include <bsd.lib.mk>
