# $FreeBSD: head/tests/etc/Makefile 289172 2015-10-12 08:16:03Z ngie $

.include <bsd.own.mk>

TESTSDIR=	${TESTSBASE}/etc

.PATH:		${SRCTOP}/tests
KYUAFILE=	yes

SUBDIR+=	rc.d

.include <bsd.test.mk>
