# $FreeBSD: head/share/vt/keymaps/Makefile 269950 2014-08-13 19:06:29Z emaste $

FILES=	be.kbd \
	fr.kbd \
	hr.kbd \
	it.kbd \
	pl.kbd \
	pt.kbd \
	si.kbd \
	ua.kbd \
	ua.shift.alt.kbd \
	uk.kbd \
	us.kbd

FILESDIR= ${SHAREDIR}/vt/keymaps

NO_OBJ=

.include <bsd.prog.mk>
