# $FreeBSD: head/lib/clang/libllvminterpreter/Makefile 296417 2016-03-05 20:24:31Z dim $

.include <bsd.own.mk>

LIB=	llvminterpreter

SRCDIR=	lib/ExecutionEngine/Interpreter
SRCS=	Execution.cpp \
	ExternalFunctions.cpp \
	Interpreter.cpp \

TGHDRS=	Attributes \
	Intrinsics

.include "../clang.lib.mk"
