# $FreeBSD: head/tests/sys/Makefile 263445 2014-03-20 20:39:41Z asomers $

.include <bsd.own.mk>

.PATH: ${.CURDIR}/..

TESTS_SUBDIRS+=		kern
TESTS_SUBDIRS+=		netinet
TESTSDIR= ${TESTSBASE}/sys

KYUAFILE= yes

.include <bsd.test.mk>
