# $FreeBSD: head/usr.sbin/bsdconfig/dot/Makefile 274073 2014-11-04 00:14:38Z dteske $

NO_OBJ=

SUBDIR= include

FILESDIR=	${LIBEXECDIR}/bsdconfig/dot
FILES=		INDEX USAGE

SCRIPTSDIR=	${FILESDIR}
SCRIPTS=	dot

.include <bsd.prog.mk>
