# $FreeBSD: head/usr.sbin/bsdconfig/usermgmt/share/Makefile 263150 2014-03-14 03:42:05Z dteske $

NO_OBJ=

FILESDIR=	${SHAREDIR}/bsdconfig/usermgmt
FILES=		group.subr group_input.subr user.subr user_input.subr

beforeinstall:
	mkdir -p ${DESTDIR}${FILESDIR}

.include <bsd.prog.mk>
