# $FreeBSD: head/usr.sbin/bsdconfig/usermgmt/share/Makefile 274073 2014-11-04 00:14:38Z dteske $

NO_OBJ=

FILESDIR=	${SHAREDIR}/bsdconfig/usermgmt
FILES=		group.subr group_input.subr user.subr user_input.subr

.include <bsd.prog.mk>
