# $FreeBSD: head/usr.sbin/bsdinstall/Makefile 288266 2015-09-26 14:13:51Z bdrewery $

SUBDIR= distextract distfetch partedit scripts
SUBDIR_PARALLEL=
SCRIPTS= bsdinstall
MAN= bsdinstall.8

.include <bsd.prog.mk>
