# $FreeBSD: head/lib/clang/libllvmorcjit/Makefile 283770 2015-05-30 15:39:49Z dim $

.include <bsd.own.mk>

LIB=	llvmorcjit

SRCDIR=	lib/ExecutionEngine/Orc
SRCS=	ExecutionUtils.cpp \
	IndirectionUtils.cpp \
	OrcMCJITReplacement.cpp \
	OrcTargetSupport.cpp

.include "../clang.lib.mk"
