# $FreeBSD: head/usr.sbin/camdd/Makefile 292687 2015-12-24 11:43:32Z bapt $

PROG=	camdd
SRCS=	camdd.c
SDIR=	${.CURDIR}/../../sys
LIBADD=	cam mt util pthread
NO_WTHREAD_SAFETY=	1
MAN=	camdd.8

.include <bsd.prog.mk>
