#	@(#)Makefile	8.1 (Berkeley) 6/4/93
# $FreeBSD: head/libexec/fingerd/Makefile 275077 2014-11-25 21:18:18Z bapt $

PROG=	fingerd
LIBADD=	util
MAN=	fingerd.8

WARNS?=	2
WFORMAT=0

.include <bsd.prog.mk>
