# $FreeBSD: head/lib/clang/libllvmasmparser/Makefile 296417 2016-03-05 20:24:31Z dim $

.include <bsd.own.mk>

LIB=	llvmasmparser

SRCDIR=	lib/AsmParser
SRCS=	LLLexer.cpp \
	LLParser.cpp \
	Parser.cpp

TGHDRS=	Attributes

.include "../clang.lib.mk"
