# $FreeBSD: head/share/man/man4/man4.arm/Makefile 263693 2014-03-24 20:06:27Z loos $

MAN=	devcfg.4 \
	mge.4 \
	npe.4 \
	ti_adc.4

MLINKS= mge.4 if_mge.4
MLINKS+=npe.4 if_npe.4

MANSUBDIR=/arm

.include <bsd.prog.mk>
