# $FreeBSD: head/usr.sbin/bsdconfig/security/include/Makefile 274073 2014-11-04 00:14:38Z dteske $

NO_OBJ=

FILESDIR=	${LIBEXECDIR}/bsdconfig/130.security/include
FILES=		messages.subr securelevel.hlp

.include <bsd.prog.mk>
