# $FreeBSD: head/sys/modules/md/Makefile 296574 2016-03-09 19:36:25Z sobomax $

.PATH: ${.CURDIR}/../../dev/md

KMOD=	geom_md
SRCS=	md.c opt_md.h opt_geom.h opt_rootdevname.h vnode_if.h

.include <bsd.kmod.mk>
