# $FreeBSD: head/usr.sbin/ctm/ctm_dequeue/Makefile 264400 2014-04-13 05:21:56Z imp $

.PATH: ${.CURDIR}/../ctm_rmail

PROG=	ctm_dequeue
MAN=
SRCS=	ctm_dequeue.c error.c

CFLAGS+= -I${.CURDIR}/../ctm_rmail

WARNS?=	1

.include <bsd.prog.mk>
