# $FreeBSD: head/lib/clang/liblldbPluginABISysV_arm/Makefile 285116 2015-07-04 01:02:43Z emaste $

.include <bsd.own.mk>

LIB=	lldbPluginABISysV_arm

SRCDIR=	tools/lldb/source/Plugins/ABI/SysV-arm
SRCS=	ABISysV_arm.cpp

TGHDRS=	DiagnosticCommonKinds \
	DeclNodes \
	StmtNodes \
	CommentCommandList

.include "../lldb.lib.mk"
