#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: head/usr.bin/vmstat/Makefile 275042 2014-11-25 14:29:10Z bapt $

PROG=	vmstat
MAN=	vmstat.8
LIBADD=	devstat kvm memstat util

WARNS?=	1

.include <bsd.prog.mk>
