#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: head/usr.bin/vmstat/Makefile 291090 2015-11-20 05:15:34Z rodrigc $

PROG=	vmstat
MAN=	vmstat.8
LIBADD=	devstat kvm memstat xo util

WARNS?=	1

.include <bsd.prog.mk>
