#$FreeBSD: head/share/dtrace/toolkit/Makefile 269764 2014-08-09 20:25:17Z jmg $
#
# Install scripts from the DTraceToolkit
#
DTRACETOOLKIT= ../../../cddl/contrib/dtracetoolkit

SCRIPTS=	${DTRACETOOLKIT}/execsnoop \
		${DTRACETOOLKIT}/hotkernel \
		${DTRACETOOLKIT}/hotuser   \
		${DTRACETOOLKIT}/opensnoop \
		${DTRACETOOLKIT}/procsystime

SCRIPTSDIR= ${SHAREDIR}/dtrace/toolkit

NO_OBJ=

.include <bsd.prog.mk>
