#$FreeBSD: head/share/dtrace/toolkit/Makefile 284255 2015-06-11 04:22:17Z sjg $
#
# Install scripts from the DTraceToolkit
#
DTRACETOOLKIT= ../../../cddl/contrib/dtracetoolkit

SCRIPTS=	${DTRACETOOLKIT}/execsnoop \
		${DTRACETOOLKIT}/hotkernel \
		${DTRACETOOLKIT}/hotuser   \
		${DTRACETOOLKIT}/opensnoop \
		${DTRACETOOLKIT}/procsystime

SCRIPTSDIR= ${SHAREDIR}/dtrace/toolkit

.include <bsd.prog.mk>
