# $FreeBSD: head/lib/clang/libllvmirreader/Makefile 296417 2016-03-05 20:24:31Z dim $

.include <bsd.own.mk>

LIB=	llvmirreader

SRCDIR=	lib/IRReader
SRCS=	IRReader.cpp

TGHDRS=	Attributes

.include "../clang.lib.mk"
