# $FreeBSD: head/lib/libclang_rt/asan-preinit/Makefile 287626 2015-09-10 20:35:47Z dim $

.include <bsd.init.mk>

LIB=	clang_rt.asan-preinit-${CRTARCH}

.PATH:	${CRTSRC}/lib/asan

SRCS=	asan_preinit.cc

.include <bsd.lib.mk>
