# $FreeBSD: head/lib/libopenbsd/Makefile 292024 2015-12-09 19:25:45Z rodrigc $

LIB=	openbsd
SRCS=	getdtablecount.c \
	imsg-buffer.c \
	imsg.c \
	ohash.c
INTERNALLIB=

CFLAGS+= -I${.CURDIR}

WARNS=	3

.include <bsd.lib.mk>
