# $FreeBSD: head/gnu/usr.bin/groff/src/utils/addftinfo/Makefile 267233 2014-06-08 17:29:31Z bdrewery $

PROG_CXX=	addftinfo
SRCS=		addftinfo.cpp guess.cpp
DPADD=		${LIBGROFF}
LDADD=		${LIBGROFF}
CLEANFILES=	${MAN}

NO_PIE=	yes

.include <bsd.prog.mk>
