# $FreeBSD: head/lib/clang/libllvmexecutionengine/Makefile 261991 2014-02-16 19:44:07Z dim $

.include <bsd.own.mk>

LIB=	llvmexecutionengine

SRCDIR=	lib/ExecutionEngine
SRCS=	ExecutionEngine.cpp \
	ExecutionEngineBindings.cpp \
	RTDyldMemoryManager.cpp \
	TargetSelect.cpp

.include "../clang.lib.mk"
