# $FreeBSD: head/lib/clang/libllvmexecutionengine/Makefile 296417 2016-03-05 20:24:31Z dim $

.include <bsd.own.mk>

LIB=	llvmexecutionengine

SRCDIR=	lib/ExecutionEngine
SRCS=	ExecutionEngine.cpp \
	ExecutionEngineBindings.cpp \
	GDBRegistrationListener.cpp \
	SectionMemoryManager.cpp \
	TargetSelect.cpp

TGHDRS=	Attributes

.include "../clang.lib.mk"
