#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: head/usr.sbin/lpr/filters/Makefile 264400 2014-04-13 05:21:56Z imp $

BINDIR=	/usr/libexec/lpr

PROG=	lpf
MAN=

CFLAGS+= -I${.CURDIR}/../common_source

.include <bsd.prog.mk>
