# $FreeBSD: head/usr.sbin/bsdconfig/password/include/Makefile 274073 2014-11-04 00:14:38Z dteske $

NO_OBJ=

FILESDIR=	${LIBEXECDIR}/bsdconfig/040.password/include
FILES=		messages.subr

.include <bsd.prog.mk>
