# $FreeBSD: head/share/doc/legal/intel_ipw/Makefile 284321 2015-06-12 14:30:27Z sjg $

FILES=		${.CURDIR}/../../../../sys/contrib/dev/ipw/LICENSE
FILESDIR=	${SHAREDIR}/doc/legal/intel_ipw

.include <bsd.prog.mk>
