# $FreeBSD: head/tests/sys/netinet/Makefile 299094 2016-05-04 23:20:53Z ngie $

TESTSDIR=	${TESTSBASE}/sys/netinet
BINDIR=		${TESTSDIR}

ATF_TESTS_SH=	fibs_test

PROGS=	udp_dontroute

MAN=

WARNS?=	6

.include <bsd.test.mk>
