# $FreeBSD: head/tests/sys/netinet/Makefile 274267 2014-11-08 03:20:56Z ngie $

TESTSDIR=	${TESTSBASE}/sys/netinet
BINDIR=		${TESTSDIR}

ATF_TESTS_SH=	fibs_test
PROGS=	udp_dontroute
MAN=
WARNS?=	6

.include <bsd.test.mk>
