# $FreeBSD: head/tests/sys/netinet/Makefile 265836 2014-05-10 16:38:37Z imp $

TESTSDIR=	${TESTSBASE}/sys/netinet
BINDIR=		${TESTSDIR}

ATF_TESTS_SH+=	fibs_test
PROG=	udp_dontroute
SRCS=	udp_dontroute.c
MAN=
WARNS?=	6

.include <bsd.test.mk>
