# $FreeBSD: head/sys/modules/geom/geom_part/geom_part_mbr/Makefile 285068 2015-07-03 01:50:26Z imp $

.PATH: ${.CURDIR}/../../../../geom/part

KMOD=	geom_part_mbr
SRCS=	g_part_mbr.c

SRCS+=	bus_if.h device_if.h g_part_if.h

.include <bsd.kmod.mk>
