#
# $FreeBSD: head/tools/regression/sockets/accf_data_attach/Makefile 264400 2014-04-13 05:21:56Z imp $
#

PROG=	accf_data_attach
MAN=

accf_data_attach: accf_data_attach.c
	gcc -Wall -o accf_data_attach accf_data_attach.c

.include <bsd.prog.mk>
