# $FreeBSD: head/lib/clang/liblldbPluginABISysV_i386/Makefile 285116 2015-07-04 01:02:43Z emaste $

.include <bsd.own.mk>

LIB=	lldbPluginABISysV_i386

SRCDIR=	tools/lldb/source/Plugins/ABI/SysV-i386
SRCS=	ABISysV_i386.cpp

TGHDRS=	DiagnosticCommonKinds \
	DeclNodes \
	StmtNodes \
	CommentCommandList

.include "../lldb.lib.mk"
