# $FreeBSD: head/usr.bin/tests/Makefile 263227 2014-03-16 08:04:06Z jmmv $

.include <bsd.own.mk>

TESTSDIR=	${TESTSBASE}/usr.bin

.PATH:		${.CURDIR:H:H}/tests
KYUAFILE=	yes

FILESDIR=	${TESTSDIR}
FILES=		regress.m4

.include <bsd.test.mk>
