# $FreeBSD: head/share/examples/smbfs/Makefile 291347 2015-11-26 01:14:27Z bdrewery $

FILESDIR= ${SHAREDIR}/examples/smbfs
FILES=	dot.nsmbrc

.PATH: ${.CURDIR}/../../../contrib/smbfs/examples

SUBDIR=	print

.include <bsd.prog.mk>
