# $FreeBSD: head/sys/modules/ow/ow_temp/Makefile 287225 2015-08-27 23:33:38Z imp $

.PATH: ${.CURDIR}/../../../dev/ow

KMOD=	ow_temp
SRCS=	ow_temp.c
SRCS+=	own_if.h bus_if.h device_if.h

.include <bsd.kmod.mk>
