# $FreeBSD: head/lib/libnetbsd/Makefile 298107 2016-04-16 07:45:30Z gjb $

.include <bsd.own.mk>

PACKAGE=lib${LIB}
LIB=	netbsd

CFLAGS+=	-I${.CURDIR}

SRCS+=	strsuftoll.c util.c util.h

INTERNALLIB=

.include <bsd.lib.mk>
