# $FreeBSD: head/sys/modules/ip_mroute_mod/Makefile 269540 2014-08-04 22:37:02Z imp $

.PATH: ${.CURDIR}/../../netinet ${.CURDIR}/../../netinet6

KMOD=	ip_mroute

SRCS=	ip_mroute.c
SRCS+=	opt_inet.h opt_mrouting.h

.include <bsd.kmod.mk>
