# $FreeBSD: head/usr.sbin/bsdconfig/timezone/share/Makefile 274073 2014-11-04 00:14:38Z dteske $

NO_OBJ=

FILESDIR=	${SHAREDIR}/bsdconfig/timezone
FILES=		continents.subr countries.subr iso3166.subr menus.subr \
		zones.subr

.include <bsd.prog.mk>
