# $FreeBSD: head/usr.bin/clang/llvm-ar/Makefile 261991 2014-02-16 19:44:07Z dim $

.include <bsd.own.mk>

PROG_CXX=llvm-ar

SRCDIR=	tools/llvm-ar
SRCS=	llvm-ar.cpp

LIBDEPS=llvmobject \
	llvmbitreader \
	llvmcore \
	llvmsupport

.include "../clang.prog.mk"
