# $FreeBSD: head/lib/clang/liblldbPluginABISysV_mips/Makefile 285116 2015-07-04 01:02:43Z emaste $

.include <bsd.own.mk>

LIB=	lldbPluginABISysV_mips

SRCDIR=	tools/lldb/source/Plugins/ABI/SysV-mips
SRCS=	ABISysV_mips.cpp

TGHDRS=	DiagnosticCommonKinds \
	DeclNodes \
	StmtNodes \
	CommentCommandList

.include "../lldb.lib.mk"
