#	$NetBSD: Makefile,v 1.14 1996/09/27 22:38:37 christos Exp $
# $FreeBSD: head/sbin/fsck/Makefile 267233 2014-06-08 17:29:31Z bdrewery $

PROG=	fsck
SRCS=	fsck.c fsutil.c preen.c
MAN=	fsck.8

NO_PIE=	yes

.include <bsd.prog.mk>
