#	$NetBSD: Makefile,v 1.14 1996/09/27 22:38:37 christos Exp $
# $FreeBSD: head/sbin/fsck/Makefile 270168 2014-08-19 15:04:32Z bdrewery $

PROG=	fsck
SRCS=	fsck.c fsutil.c preen.c
MAN=	fsck.8

.include <bsd.prog.mk>
