# $FreeBSD: head/usr.sbin/bsdconfig/share/Makefile 274073 2014-11-04 00:14:38Z dteske $

NO_OBJ=

SUBDIR=	media packages

FILESDIR=	${SHAREDIR}/bsdconfig
FILES=		common.subr device.subr dialog.subr geom.subr keymap.subr \
		mustberoot.subr script.subr strings.subr struct.subr \
		sysrc.subr variable.subr

.include <bsd.prog.mk>
