# $FreeBSD: head/sys/modules/if_lagg/Makefile 269540 2014-08-04 22:37:02Z imp $

.PATH:	${.CURDIR}/../../net
KMOD=	if_lagg
SRCS=	if_lagg.c ieee8023ad_lacp.c opt_inet.h opt_inet6.h

.include <bsd.kmod.mk>
