# $FreeBSD: head/lib/clang/libclangfrontendtool/Makefile 280031 2015-03-15 13:31:13Z dim $

.include <bsd.own.mk>

LIB=	clangfrontendtool

SRCDIR=	tools/clang/lib/FrontendTool
SRCS=	ExecuteCompilerInvocation.cpp

TGHDRS=	CommentCommandList \
	DeclNodes \
	DiagnosticCommonKinds \
	DiagnosticFrontendKinds \
	Options \
	StmtNodes

.include "../clang.lib.mk"
