# $FreeBSD: head/lib/clang/libllvmpowerpcinfo/Makefile 296417 2016-03-05 20:24:31Z dim $

.include <bsd.own.mk>

LIB=	llvmpowerpcinfo

SRCDIR=	lib/Target/PowerPC/TargetInfo
INCDIR=	lib/Target/PowerPC
SRCS=	PowerPCTargetInfo.cpp

TGHDRS=	Attributes \
	PPCGenInstrInfo \
	PPCGenRegisterInfo \
	PPCGenSubtargetInfo

.include "../clang.lib.mk"
