# $FreeBSD: head/sys/boot/userboot/libstand/Makefile 293435 2016-01-08 19:12:26Z emaste $

.include <src.opts.mk>

LIBSTAND_SRC=	${.CURDIR}/../../../../lib/libstand

INTERNALLIB=
INCS=
MAN=
.PATH:	${LIBSTAND_SRC}

.include "${LIBSTAND_SRC}/Makefile"
