#	@(#)Makefile	8.1 (Berkeley) 5/31/93
# $FreeBSD: head/games/primes/Makefile 272166 2014-09-26 09:40:48Z cperciva $

PROG=	primes
SRCS=	pattern.c pr_tbl.c primes.c spsp.c
MAN=
DPADD=	${LIBM}
LDADD=	-lm

.include <bsd.prog.mk>
