#	@(#)Makefile	8.1 (Berkeley) 5/31/93
# $FreeBSD: head/games/primes/Makefile 264400 2014-04-13 05:21:56Z imp $

PROG=	primes
SRCS=	pattern.c pr_tbl.c primes.c
MAN=
DPADD=	${LIBM}
LDADD=	-lm

.include <bsd.prog.mk>
