# $FreeBSD: head/usr.bin/lastcomm/tests/Makefile 299094 2016-05-04 23:20:53Z ngie $

PACKAGE=	tests

TAP_TESTS_SH=	legacy_test

${PACKAGE}FILES+=		v1-amd64-acct.in
${PACKAGE}FILES+=		v1-amd64.out
${PACKAGE}FILES+=		v1-i386-acct.in
${PACKAGE}FILES+=		v1-i386.out
${PACKAGE}FILES+=		v1-sparc64-acct.in
${PACKAGE}FILES+=		v1-sparc64.out
${PACKAGE}FILES+=		v2-amd64-acct.in
${PACKAGE}FILES+=		v2-amd64.out
${PACKAGE}FILES+=		v2-i386-acct.in
${PACKAGE}FILES+=		v2-i386.out
${PACKAGE}FILES+=		v2-sparc64-acct.in
${PACKAGE}FILES+=		v2-sparc64.out

.include <bsd.test.mk>
