# $FreeBSD: head/usr.sbin/ntp/doc/drivers/icons/Makefile 280849 2015-03-30 13:30:15Z cy $

.include <src.opts.mk>

FILESDIR=	${SHAREDIR}/doc/ntp/drivers/icons

.if ${MK_HTML} != "no"
FILES=	home.gif mail2.gif
.endif

.PATH: ${.CURDIR}/../../../../../contrib/ntp/html/drivers/icons

.include <bsd.prog.mk>
