# $FreeBSD: head/lib/libc/tests/Makefile.netbsd-tests 274075 2014-11-04 00:56:25Z ngie $

OBJTOP?=	${.OBJDIR:H:H:H:H}
SRCTOP?=	${.CURDIR:H:H:H:H}
TESTSRC?=	${SRCTOP}/contrib/netbsd-tests/lib/libc/${.CURDIR:T}

.include <netbsd-tests.test.mk>
