# $FreeBSD: head/usr.bin/mkuzip/Makefile 295943 2016-02-23 23:59:08Z sobomax $

PROG=	mkuzip
MAN=	mkuzip.8
SRCS=	mkuzip.c mkuz_blockcache.c mkuz_lzma.c mkuz_zlib.c

LIBADD=	z md lzma

.include <bsd.prog.mk>
