# $FreeBSD: head/usr.sbin/bsdinstall/distextract/Makefile 275874 2014-12-18 03:51:09Z dteske $

BINDIR= /usr/libexec/bsdinstall
PROG=	distextract
LIBADD=	archive dpv figpar ncursesw dialog m

WARNS?=	6
MAN=

.include <bsd.prog.mk>
