# $FreeBSD: head/lib/clang/libllvmjit/Makefile 261991 2014-02-16 19:44:07Z dim $

.include <bsd.own.mk>

LIB=	llvmjit

SRCDIR=	lib/ExecutionEngine/JIT
SRCS=	JIT.cpp \
	JITEmitter.cpp \
	JITMemoryManager.cpp

.include "../clang.lib.mk"
