# $FreeBSD: head/tools/tools/npe/npestats/Makefile 264400 2014-04-13 05:21:56Z imp $

PROG=	npestats
SRCS=	main.c npestats.c
BINDIR=	/usr/local/bin
MAN=
USEPRIVATELIB=
LDADD=	-lbsdstat

.include <bsd.prog.mk>
