# $FreeBSD: head/lib/clang/liblldbPluginInstructionARM64/Makefile 275132 2014-11-26 17:40:03Z emaste $

.include <bsd.own.mk>

LIB=	lldbPluginInstructionARM64

SRCDIR=	tools/lldb/source/Plugins/Instruction/ARM64
SRCS=	EmulateInstructionARM64.cpp

.include "../lldb.lib.mk"
