# $FreeBSD: head/sbin/devd/tests/Makefile 289172 2015-10-12 08:16:03Z ngie $

ATF_TESTS_C=	client_test
TEST_METADATA.client_test=	required_programs="devd"
TEST_METADATA.client_test+=	required_user="root"
TEST_METADATA.client_test+=	timeout=15

WARNS?=	5

.include <bsd.test.mk>
