# $FreeBSD: head/usr.bin/soelim/tests/Makefile 289172 2015-10-12 08:16:03Z ngie $

ATF_TESTS_SH=	soelim

FILES=		nonexisting.in \
		basic.in \
		basic \
		basic.out \
		basic-with-space.in \
		basic-with-space.out
FILESDIR=	${TESTSDIR}

.include <bsd.test.mk>
