# $FreeBSD: head/usr.bin/soelim/tests/Makefile 282425 2015-05-04 18:20:31Z bapt $

TESTSDIR=	${TESTSBASE}/usr.bin/soelim

ATF_TESTS_SH=	soelim

FILES=		nonexisting.in \
		basic.in \
		basic \
		basic.out \
		basic-with-space.in \
		basic-with-space.out
FILESDIR=	${TESTSDIR}

.include <bsd.test.mk>
