# $FreeBSD: head/usr.bin/soelim/tests/Makefile 299094 2016-05-04 23:20:53Z ngie $

PACKAGE=	tests

ATF_TESTS_SH=	soelim

${PACKAGE}FILES+=		nonexisting.in \
		basic.in \
		basic \
		basic.out \
		basic-with-space.in \
		basic-with-space.out

.include <bsd.test.mk>
