# $FreeBSD: head/tools/regression/kqueue/Makefile 264400 2014-04-13 05:21:56Z imp $
#
# svn://mark.heily.com/libkqueue/trunk/test
# Last update: r114
#
# libkqueue and test suite by Mark Heily <mark@heily.com>
#

PROG=kqtest
SRCS=			\
	main.c		\
	read.c		\
	timer.c		\
	vnode.c		\
	proc.c		\
	signal.c	\
	user.c
MAN=
WARNS?=	2

.include "bsd.prog.mk"
