# $FreeBSD: head/lib/clang/libllvmsparcinfo/Makefile 296417 2016-03-05 20:24:31Z dim $

.include <bsd.own.mk>

LIB=	llvmsparcinfo

SRCDIR=	lib/Target/Sparc/TargetInfo
INCDIR=	lib/Target/Sparc
SRCS=	SparcTargetInfo.cpp

TGHDRS=	Attributes \
	SparcGenInstrInfo \
	SparcGenRegisterInfo \
	SparcGenSubtargetInfo

.include "../clang.lib.mk"
