#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: head/sbin/shutdown/Makefile 270289 2014-08-21 19:04:15Z neel $

PROG=	shutdown
MAN=	shutdown.8
LINKS=	${BINDIR}/shutdown ${BINDIR}/poweroff
MLINKS=	shutdown.8 poweroff.8

BINOWN=	root
BINGRP=	operator
BINMODE=4554

.include <bsd.prog.mk>
