# $FreeBSD: head/usr.bin/make/tests/execution/empty/Makefile 263348 2014-03-19 12:32:50Z jmmv $

TESTSDIR=	${TESTSBASE}/usr.bin/make/execution/empty

TAP_TESTS_SH=	legacy_test

FILESDIR=	${TESTSDIR}
FILES=		Makefile.test
FILES+=		expected.status.1
FILES+=		expected.stderr.1
FILES+=		expected.stdout.1

.include <bsd.test.mk>
