# $FreeBSD: head/tools/tools/net80211/wesside/wesside/Makefile 264400 2014-04-13 05:21:56Z imp $

PROG=	wesside
BINDIR=	/usr/local/bin
DPADD=	${LIBZ}
LDADD=	-lz
CFLAGS=-g
MAN=
SRCS=wesside.c aircrack-ptw-lib.c

.include <bsd.prog.mk>
