# $FreeBSD: head/sbin/geom/class/multipath/Makefile 298107 2016-04-16 07:45:30Z gjb $

PACKAGE=runtime
.PATH: ${.CURDIR}/../../misc

GEOM_CLASS=	multipath

CFLAGS+=  -I${.CURDIR}/../../../../sys

.include <bsd.lib.mk>
