# $FreeBSD: head/usr.sbin/bsdconfig/console/Makefile 274073 2014-11-04 00:14:38Z dteske $

NO_OBJ=

SUBDIR= include

FILESDIR=	${LIBEXECDIR}/bsdconfig/080.console
FILES=		INDEX USAGE

SCRIPTSDIR=	${FILESDIR}
SCRIPTS=	console font keymap repeat saver screenmap ttys

.include <bsd.prog.mk>
