# $FreeBSD: head/sbin/geom/class/virstor/Makefile 298107 2016-04-16 07:45:30Z gjb $

PACKAGE=runtime
.PATH: ${.CURDIR}/../../misc ${.CURDIR}/../../../../sys/geom/virstor

GEOM_CLASS=	virstor

SRCS+=	binstream.c
SRCS+=	g_virstor_md.c

.include <bsd.lib.mk>
