# $FreeBSD: head/kerberos5/libexec/Makefile 288266 2015-09-26 14:13:51Z bdrewery $

SUBDIR=	digest-service ipropd-master ipropd-slave hprop hpropd kadmind kdc \
	kdigest kfd kimpersonate kpasswdd kcm
SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
