# $FreeBSD: head/usr.sbin/bsdconfig/includes/include/Makefile 258400 2013-11-20 20:37:21Z dteske $

NO_OBJ=

FILESDIR=	${LIBEXECDIR}/bsdconfig/includes/include
FILES=		messages.subr

beforeinstall:
	mkdir -p ${DESTDIR}${FILESDIR}

.include <bsd.prog.mk>
