# $FreeBSD: head/usr.bin/make/tests/execution/Makefile 263348 2014-03-19 12:32:50Z jmmv $

TESTSDIR=	${TESTSBASE}/usr.bin/make/execution

TESTS_SUBDIRS=	ellipsis empty joberr plus

.include <bsd.test.mk>
