# $FreeBSD: head/usr.sbin/pw/tests/Makefile 272578 2014-10-06 00:16:23Z brd $

TESTSDIR=	${TESTSBASE}/usr.sbin/pw

ATF_TESTS_SH=	pw_delete pw_modify

FILES=		group helper_functions.shin master.passwd
FILESDIR=       ${TESTSDIR}

.include <bsd.test.mk>
