# $FreeBSD: head/usr.bin/uudecode/tests/Makefile 289172 2015-10-12 08:16:03Z ngie $

TAP_TESTS_SH=	legacy_test

FILESDIR=	${TESTSDIR}
FILES=		regress.base64.in
FILES+=		regress.out
FILES+=		regress.sh
FILES+=		regress.traditional.in

.include <bsd.test.mk>
