# $FreeBSD: head/usr.bin/bzip2recover/Makefile 264400 2014-04-13 05:21:56Z imp $

BZ2DIR=	${.CURDIR}/../../contrib/bzip2
.PATH: ${BZ2DIR}

PROG=	bzip2recover
MAN=

NO_WMISSING_VARIABLE_DECLARATIONS=

.include <bsd.prog.mk>
