# $FreeBSD: head/lib/clang/libllvmmcjit/Makefile 296417 2016-03-05 20:24:31Z dim $

.include <bsd.own.mk>

LIB=	llvmmcjit

SRCDIR=	lib/ExecutionEngine/MCJIT
SRCS=	MCJIT.cpp

TGHDRS=	Attributes

.include "../clang.lib.mk"
