# $FreeBSD: head/lib/clang/libllvmmcjit/Makefile 288943 2015-10-06 17:53:29Z dim $

.include <bsd.own.mk>

LIB=	llvmmcjit

SRCDIR=	lib/ExecutionEngine/MCJIT
SRCS=	MCJIT.cpp

.include "../clang.lib.mk"
