#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: head/usr.sbin/iostat/Makefile 275054 2014-11-25 16:57:27Z bapt $

PROG=	iostat
MAN=	iostat.8

LIBADD=	devstat kvm m

WARNS?=	1

.include <bsd.prog.mk>
