# $FreeBSD: head/lib/clang/liblldbPluginABISysV_arm64/Makefile 285116 2015-07-04 01:02:43Z emaste $

.include <bsd.own.mk>

LIB=	lldbPluginABISysV_arm64

SRCDIR=	tools/lldb/source/Plugins/ABI/SysV-arm64
SRCS=	ABISysV_arm64.cpp

TGHDRS=	DiagnosticCommonKinds \
	DeclNodes \
	StmtNodes \
	CommentCommandList

.include "../lldb.lib.mk"
