# $FreeBSD: head/lib/clang/libllvmlto/Makefile 296417 2016-03-05 20:24:31Z dim $

.include <src.opts.mk>

LIB=	llvmlto

SRCDIR=	lib/LTO
SRCS=	LTOCodeGenerator.cpp \
	LTOModule.cpp

TGHDRS=	Attributes \
	Intrinsics

.include "../clang.lib.mk"
