# $FreeBSD: head/lib/clang/libllvmlto/Makefile 283770 2015-05-30 15:39:49Z dim $

.include <src.opts.mk>

LIB=	llvmlto

SRCDIR=	lib/LTO
SRCS=	LTOCodeGenerator.cpp \
	LTOModule.cpp

TGHDRS=	Intrinsics

.include "../clang.lib.mk"
