# $FreeBSD: head/sys/modules/ow/ow/Makefile 287225 2015-08-27 23:33:38Z imp $

.PATH: ${.CURDIR}/../../../dev/ow

KMOD=	ow
SRCS=	ow.c
SRCS+=	own_if.c own_if.h owll_if.c owll_if.h bus_if.h device_if.h

.include <bsd.kmod.mk>
