# $FreeBSD: head/share/doc/legal/intel_wpi/Makefile 284321 2015-06-12 14:30:27Z sjg $

FILES=          ${.CURDIR}/../../../../sys/contrib/dev/wpi/LICENSE
FILESDIR=       ${SHAREDIR}/doc/legal/intel_wpi

.include <bsd.prog.mk>

