# $FreeBSD: head/usr.bin/make/tests/shell/Makefile 263348 2014-03-19 12:32:50Z jmmv $

TESTSDIR=	${TESTSBASE}/usr.bin/make/shell

TESTS_SUBDIRS=	builtin meta path path_select replace select

.include <bsd.test.mk>
