# $FreeBSD: head/sys/modules/trm/Makefile 269540 2014-08-04 22:37:02Z imp $

.PATH: ${.CURDIR}/../../dev/trm

KMOD=	trm
SRCS=	trm.c trm.h opt_cam.h device_if.h bus_if.h \
	opt_scsi.h pci_if.h

.include <bsd.kmod.mk>
