# $FreeBSD: head/lib/clang/libllvmsymbolize/Makefile 292990 2015-12-31 17:37:35Z dim $

.include <bsd.own.mk>

LIB=	llvmsymbolize

SRCDIR=	lib/DebugInfo/Symbolize
SRCS=	DIPrinter.cpp \
	SymbolizableObjectFile.cpp \
	Symbolize.cpp

.include "../clang.lib.mk"
