# $FreeBSD: head/sys/modules/mvs/Makefile 285068 2015-07-03 01:50:26Z imp $

.PATH: ${.CURDIR}/../../dev/mvs

KMOD=	mvs
SRCS=	mvs.c mvs_pci.c mvs.h mvs_if.c mvs_if.h device_if.h bus_if.h pci_if.h opt_cam.h

.include <bsd.kmod.mk>
