# $FreeBSD: head/lib/librt/tests/Makefile 289172 2015-10-12 08:16:03Z ngie $

LIBADD=	rt

NETBSD_ATF_TESTS_C=	sched_test
NETBSD_ATF_TESTS_C+=	sem_test

.include <netbsd-tests.test.mk>

.include <bsd.test.mk>
