# Makefile for ntpd.
# $FreeBSD: head/usr.sbin/ntp/Makefile 280849 2015-03-30 13:30:15Z cy $

SUBDIR=	libopts libntp libntpevent libparse ntpd ntpdc ntpq ntpdate \
	ntptime ntp-keygen sntp
SUBDIR+=	doc

.include <bsd.subdir.mk>
