# $FreeBSD: head/lib/libc/tests/inet/Makefile 289172 2015-10-12 08:16:03Z ngie $

.include <bsd.own.mk>

NETBSD_ATF_TESTS_C=	inet_network_test

.include "../Makefile.netbsd-tests"

.include <bsd.test.mk>
