# $FreeBSD: head/lib/clang/liblldbPluginInstructionMIPS64/Makefile 285116 2015-07-04 01:02:43Z emaste $

.include <bsd.own.mk>

LIB=	lldbPluginInstructionMIPS64

SRCDIR=	tools/lldb/source/Plugins/Instruction/MIPS64
SRCS=	EmulateInstructionMIPS64.cpp

TGHDRS=	DiagnosticCommonKinds \
	DeclNodes \
	StmtNodes \
	CommentCommandList

.include "../lldb.lib.mk"
