# $FreeBSD: head/sys/modules/i2c/isl/Makefile 285883 2015-07-25 20:17:19Z grembo $

.PATH:		${.CURDIR}/../../../dev/isl
KMOD		= isl
SRCS		= isl.c device_if.h bus_if.h smbus_if.h vnode_if.h

.include <bsd.kmod.mk>
