# $FreeBSD: head/usr.sbin/ntp/doc/drivers/scripts/Makefile 280849 2015-03-30 13:30:15Z cy $

.include <src.opts.mk>

FILESDIR=	${SHAREDIR}/doc/ntp/drivers/scripts

.if ${MK_HTML} != "no"
FILES=	footer.txt style.css
.endif

.PATH: ${.CURDIR}/../../../../../contrib/ntp/html/drivers/scripts

.include <bsd.prog.mk>
