# $FreeBSD: head/lib/libproc/test/t2-name2map/Makefile 264400 2014-04-13 05:21:56Z imp $

PROG=	t2-name2map

SRCS=	t2-name2map.c

LDADD=	-lproc -lelf -lrtld_db -lutil
DPADD=	${LIBPROC} ${LIBELF}

MAN=

.include <bsd.prog.mk>
