# $FreeBSD: head/usr.sbin/bsdconfig/share/media/Makefile 291347 2015-11-26 01:14:27Z bdrewery $

FILESDIR=	${SHAREDIR}/bsdconfig/media
FILES=		any.subr cdrom.subr common.subr directory.subr dos.subr \
		floppy.subr ftp.subr http.subr httpproxy.subr network.subr \
		nfs.subr options.subr tcpip.subr ufs.subr usb.subr

.include <bsd.prog.mk>
