# $FreeBSD: head/usr.sbin/bsdconfig/share/media/Makefile 274073 2014-11-04 00:14:38Z dteske $

NO_OBJ=

FILESDIR=	${SHAREDIR}/bsdconfig/media
FILES=		any.subr cdrom.subr common.subr directory.subr dos.subr \
		floppy.subr ftp.subr http.subr httpproxy.subr network.subr \
		nfs.subr options.subr tcpip.subr ufs.subr usb.subr

.include <bsd.prog.mk>
