# $FreeBSD: head/usr.sbin/bsdconfig/examples/Makefile 268999 2014-07-22 23:10:12Z dteske $

NO_OBJ=

FILESDIR=	${SHAREDIR}/examples/bsdconfig
FILES=		add_some_packages.sh browse_packages_http.sh bsdconfigrc

beforeinstall:
	mkdir -p ${DESTDIR}${FILESDIR}

.include <bsd.prog.mk>
