# $FreeBSD: head/usr.sbin/bsdconfig/examples/Makefile 274073 2014-11-04 00:14:38Z dteske $

NO_OBJ=

FILESDIR=	${SHAREDIR}/examples/bsdconfig
FILES=		add_some_packages.sh browse_packages_http.sh bsdconfigrc

.include <bsd.prog.mk>
