# $FreeBSD: head/sys/modules/dtb/imx6/Makefile 290703 2015-11-12 03:37:28Z gonzo $
# All the dts files for imx6 systems we support.
DTS=	\
	imx6dl-cubox-i.dts \
	imx6q-cubox-i.dts \
	imx6dl-hummingboard.dts \
	imx6q-hummingboard.dts \
	imx6dl-riotboard.dts \
	imx6dl-wandboard.dts \
	imx6q-wandboard.dts

.include <bsd.dtb.mk>
