# $FreeBSD: head/sys/modules/dtb/imx6/Makefile 279593 2015-03-04 16:19:34Z ian $
# All the dts files for imx6 systems we support.
DTS=	\
	imx6dl-cubox-i.dts \
	imx6q-cubox-i.dts \
	imx6dl-hummingboard.dts \
	imx6q-hummingboard.dts \
	imx6dl-wandboard.dts \
	imx6q-wandboard.dts

.include <bsd.dtb.mk>
