# $FreeBSD: head/sys/boot/forth/Makefile 281081 2015-04-04 19:56:54Z bapt $

MAN+=	beastie.4th.8 \
	brand.4th.8 \
	check-password.4th.8 \
	color.4th.8 \
	delay.4th.8 \
	loader.conf.5 \
	loader.4th.8 \
	menu.4th.8 \
	menusets.4th.8

.include <bsd.prog.mk>
