# $FreeBSD: head/sys/boot/forth/Makefile 284672 2015-06-21 06:56:29Z antoine $

MAN+=	beastie.4th.8 \
	brand.4th.8 \
	check-password.4th.8 \
	color.4th.8 \
	delay.4th.8 \
	loader.conf.5 \
	loader.4th.8 \
	menu.4th.8 \
	menusets.4th.8 \
	version.4th.8

.include <bsd.prog.mk>
