# $FreeBSD: head/lib/clang/liblldbUtility/Makefile 296417 2016-03-05 20:24:31Z dim $

.include <bsd.own.mk>

LIB=	lldbUtility

SRCDIR=	tools/lldb/source/Utility
SRCS=	ARM64_DWARF_Registers.cpp \
	ARM_DWARF_Registers.cpp \
	ConvertEnum.cpp \
	JSON.cpp \
	KQueue.cpp \
	LLDBAssert.cpp \
	ModuleCache.cpp \
	NameMatches.cpp \
	PseudoTerminal.cpp \
	Range.cpp \
	RegisterNumber.cpp \
	SharingPtr.cpp \
	StringExtractor.cpp \
	StringExtractorGDBRemote.cpp \
	StringLexer.cpp \
	TaskPool.cpp \
	TimeSpecTimeout.cpp \
	UriParser.cpp

.include "../lldb.lib.mk"
