# $FreeBSD: head/lib/clang/liblldbUtility/Makefile 258054 2013-11-12 17:25:33Z emaste $

.include <bsd.own.mk>

LIB=	lldbUtility

SRCDIR=	tools/lldb/source/Utility
SRCS=	ARM_DWARF_Registers.cpp \
	KQueue.cpp \
	PseudoTerminal.cpp \
	Range.cpp \
	SharingPtr.cpp \
	StringExtractor.cpp \
	StringExtractorGDBRemote.cpp \
	TimeSpecTimeout.cpp

.include "../lldb.lib.mk"
