# $FreeBSD: head/lib/clang/liblldbUtility/Makefile 280031 2015-03-15 13:31:13Z dim $

.include <bsd.own.mk>

LIB=	lldbUtility

SRCDIR=	tools/lldb/source/Utility
SRCS=	ARM64_DWARF_Registers.cpp \
	ARM_DWARF_Registers.cpp \
	KQueue.cpp \
	PseudoTerminal.cpp \
	Range.cpp \
	RegisterNumber.cpp \
	SharingPtr.cpp \
	StringExtractor.cpp \
	StringExtractorGDBRemote.cpp \
	StringLexer.cpp \
	TimeSpecTimeout.cpp \
	UriParser.cpp

.include "../lldb.lib.mk"
