# $FreeBSD: head/usr.bin/make/tests/archives/Makefile 263348 2014-03-19 12:32:50Z jmmv $

TESTSDIR=	${TESTSBASE}/usr.bin/make/archives

TESTS_SUBDIRS=	fmt_44bsd fmt_44bsd_mod fmt_oldbsd

.include <bsd.test.mk>
