# $FreeBSD: head/usr.bin/ident/tests/Makefile 285890 2015-07-26 11:21:36Z bapt $

TESTSDIR=	${TESTSBASE}/usr.bin/ident

ATF_TESTS_SH=	ident
FILES=		test.in \
		test.out \
		testnoid
FILESDIR=	${TESTSDIR}

.include <bsd.test.mk>
