# $FreeBSD: head/lib/clang/liblldbPluginScriptInterpreterNone/Makefile 293124 2016-01-04 00:02:58Z emaste $

.include <bsd.own.mk>

LIB=	lldbPluginScriptInterpreterNone

SRCDIR=	tools/lldb/source/Plugins/ScriptInterpreter/None
SRCS=	ScriptInterpreterNone.cpp

.include "../lldb.lib.mk"
