# $FreeBSD: head/lib/libc/tests/termios/Makefile 289172 2015-10-12 08:16:03Z ngie $

.include <bsd.own.mk>

NETBSD_ATF_TESTS_C=	tcsetpgrp_test

.include "../Makefile.netbsd-tests"

.include <bsd.test.mk>
