# $FreeBSD: head/gnu/usr.bin/groff/src/preproc/soelim/Makefile 270168 2014-08-19 15:04:32Z bdrewery $

PROG_CXX=	soelim
SRCS=		soelim.cpp
DPADD=		${LIBGROFF}
LDADD=		${LIBGROFF}
CLEANFILES=	${MAN}

.include <bsd.prog.mk>
