# $FreeBSD: head/gnu/usr.bin/groff/src/preproc/soelim/Makefile 267233 2014-06-08 17:29:31Z bdrewery $

PROG_CXX=	soelim
SRCS=		soelim.cpp
DPADD=		${LIBGROFF}
LDADD=		${LIBGROFF}
CLEANFILES=	${MAN}

NO_PIE=	yes

.include <bsd.prog.mk>
