# $FreeBSD: head/gnu/usr.bin/cc/collect2/Makefile 264400 2014-04-13 05:21:56Z imp $

.include "../Makefile.inc"

.PATH: ${GCCDIR}

PROG=	collect2
SRCS=	collect2.c tlink.c version.c
MAN=

.include <bsd.prog.mk>
