#
# $FreeBSD: head/sys/modules/tests/callout_test/Makefile 290663 2015-11-10 14:14:41Z rrs $
#

.PATH: ${.CURDIR}/../../../tests/callout_test

KMOD=	callout_test
SRCS=	callout_test.c

#
# Enable full debugging
#
#CFLAGS += -g

.include <bsd.kmod.mk>
