# $FreeBSD: head/lib/libclang_rt/asan_cxx/Makefile 276857 2015-01-08 22:40:56Z dim $

.include <bsd.init.mk>

LIB=	clang_rt.asan_cxx-${CRTARCH}

.PATH:	${CRTSRC}/lib/asan

SRCS=	asan_new_delete.cc

.include <bsd.lib.mk>
