# $FreeBSD: head/lib/libc/tests/ttyio/Makefile 291738 2015-12-04 03:17:47Z bdrewery $

.include <bsd.own.mk>

# TODO: ptm_test
NETBSD_ATF_TESTS_C=	ttyio_test

LIBADD.ttyio_test+=	util

.include "../Makefile.netbsd-tests"

.include <bsd.test.mk>
