# $FreeBSD: head/gnu/usr.bin/texinfo/infokey/Makefile 270168 2014-08-19 15:04:32Z bdrewery $

PROG=	infokey
SRCS=	infokey.c key.c

DPADD=	${LIBTXI}
LDADD=	${LIBTXI}

.include <bsd.prog.mk>

.PATH:	${TXIDIR}/info ${TXIDIR}/doc
