# $FreeBSD: head/tools/tools/mwl/mwlstats/Makefile 264400 2014-04-13 05:21:56Z imp $

PROG=	mwlstats
BINDIR=	/usr/local/bin
MAN=

SRCS=	main.c mwlstats.c
USEPRIVATELIB=
LDADD=-lbsdstat

.include <bsd.prog.mk>

CFLAGS+= -I.
