# $FreeBSD: head/tools/tools/mwl/mwlstats/Makefile 275088 2014-11-25 22:45:35Z bapt $

PROG=	mwlstats
BINDIR=	/usr/local/bin
MAN=

SRCS=	main.c mwlstats.c
LIBADD=	bsdstat

.include <bsd.prog.mk>

CFLAGS+= -I.
