# $FreeBSD: head/sys/boot/userboot/test/Makefile 264400 2014-04-13 05:21:56Z imp $


MAN=

.include <bsd.own.mk>
MK_SSP=		no

PROG=		test
INTERNALPROG=

CFLAGS+=	-I${.CURDIR}/..
CFLAGS+=	-I${.CURDIR}/../../..

.include <bsd.prog.mk>
