# ex:ts=8
#
# Makefile for amd
# 	This file is under a "BSD" copyright (c) by David O'Brien 1998
#
# $FreeBSD: head/usr.sbin/amd/Makefile 276551 2015-01-02 18:45:03Z bapt $

SUBDIR= include libamu amd amq fixmount fsinfo hlfsd mk-amd-map pawd \
	scripts wire-test

.include <bsd.subdir.mk>
