# $FreeBSD: head/usr.bin/clang/macho-dump/Makefile 264400 2014-04-13 05:21:56Z imp $

MAN=
.include <bsd.own.mk>

PROG_CXX=macho-dump

SRCDIR=	tools/macho-dump
SRCS=	macho-dump.cpp

LIBDEPS=llvmobject \
	llvmsupport

.include "../clang.prog.mk"
