# $FreeBSD: head/cddl/usr.sbin/dtrace/tests/Makefile 289172 2015-10-12 08:16:03Z ngie $

.include <bsd.own.mk>

TESTS_SUBDIRS+=	common

.PATH:		${SRCTOP}/tests
KYUAFILE=	YES

.PATH:		${.CURDIR}/tools
SCRIPTSDIR=	${TESTSDIR}
SCRIPTS=	dtest.sh

.include <bsd.test.mk>
