# $FreeBSD: head/usr.bin/make/tests/suffixes/Makefile 263348 2014-03-19 12:32:50Z jmmv $

TESTSDIR=	${TESTSBASE}/usr.bin/make/suffixes

TESTS_SUBDIRS=	basic src_wild1 src_wild2

.include <bsd.test.mk>
