# $FreeBSD: head/usr.sbin/ntp/doc/icons/Makefile 280849 2015-03-30 13:30:15Z cy $

.include <src.opts.mk>

FILESDIR=	${SHAREDIR}/doc/ntp/icons

.if ${MK_HTML} != "no"
FILES=	home.gif mail2.gif sitemap.png
.endif

.PATH: ${.CURDIR}/../../../../contrib/ntp/html/icons

.include <bsd.prog.mk>
