# $FreeBSD: head/sys/modules/i2c/cyapa/Makefile 285876 2015-07-25 18:14:35Z grembo $

.PATH:		${.CURDIR}/../../../dev/cyapa
KMOD		= cyapa
SRCS		= cyapa.c device_if.h bus_if.h smbus_if.h vnode_if.h

.include <bsd.kmod.mk>
