# $FreeBSD: head/secure/lib/libcrypto/engines/Makefile 290207 2015-10-30 20:51:33Z jkim $

SUBDIR=	lib4758cca libaep libatalla libcapi libchil libcswift libgost \
	libnuron libsureware libubsec

.include <bsd.subdir.mk>
