# $FreeBSD: head/etc/autofs/Makefile 279955 2015-03-13 12:44:46Z trasz $

FILES=		include_ldap special_hosts special_media special_noauto special_null

NO_OBJ=
FILESDIR=	/etc/autofs
FILESMODE=	755

.include <bsd.prog.mk>
