# $FreeBSD: head/lib/libutil/tests/Makefile 275024 2014-11-25 11:07:26Z bapt $

TESTSDIR=	${TESTSBASE}/lib/libutil

TAP_TESTS_C+=	flopen_test
TAP_TESTS_C+=	grp_test
TAP_TESTS_C+=	humanize_number_test
TAP_TESTS_C+=	pidfile_test
TAP_TESTS_C+=	trimdomain_test
TAP_TESTS_C+=	trimdomain-nodomain_test

LIBADD+=	util

.include <bsd.test.mk>
