#	@(#)Makefile	8.1 (Berkeley) 7/19/93
# $FreeBSD: head/usr.bin/rsh/Makefile 279603 2015-03-04 22:01:44Z bapt $

PROG=	rsh
CFLAGS+=-I${.CURDIR}/../../libexec/rlogind

WARNS?=	2

BINOWN=	root
BINMODE=4555

.include <bsd.prog.mk>
