#	@(#)Makefile	8.1 (Berkeley) 7/19/93
# $FreeBSD: head/usr.bin/rsh/Makefile 284065 2015-06-06 12:43:05Z bapt $

PROG=	rsh
CFLAGS+=-I${.CURDIR}/../../libexec/rlogind

BINOWN=	root
BINMODE=4555

.include <bsd.prog.mk>
