#	@(#)Makefile	8.1 (Berkeley) 7/19/93
# $FreeBSD: head/usr.bin/rsh/Makefile 298107 2016-04-16 07:45:30Z gjb $

PROG=	rsh
CFLAGS+=-I${.CURDIR}/../../libexec/rlogind

PACKAGE=rcmds

BINOWN=	root
BINMODE=4555

.include <bsd.prog.mk>
