# $FreeBSD: head/sys/modules/dtb/allwinner/Makefile 281799 2015-04-20 22:12:19Z loos $
# All the dts files for allwinner systems we support.
DTS=	\
	cubieboard.dts \
	cubieboard2.dts

.include <bsd.dtb.mk>
