# $FreeBSD: head/sys/modules/dtb/allwinner/Makefile 295464 2016-02-10 09:19:29Z andrew $
# All the dts files for allwinner systems we support.
DTS=	\
	bananapi.dts \
	cubieboard.dts \
	cubieboard2.dts \
	olimex-a20-som-evb.dts \
	olinuxino-lime.dts

.include <bsd.dtb.mk>
