# $FreeBSD: head/sys/modules/dtb/allwinner/Makefile 285250 2015-07-07 19:01:54Z loos $
# All the dts files for allwinner systems we support.
DTS=	\
	bananapi.dts \
	cubieboard.dts \
	cubieboard2.dts

.include <bsd.dtb.mk>
