# $FreeBSD: head/lib/clang/libllvmruntimedyld/Makefile 288943 2015-10-06 17:53:29Z dim $

.include <bsd.own.mk>

LIB=	llvmruntimedyld

SRCDIR=	lib/ExecutionEngine/RuntimeDyld
SRCS=	RTDyldMemoryManager.cpp \
	RuntimeDyld.cpp \
	RuntimeDyldCOFF.cpp \
	RuntimeDyldChecker.cpp \
	RuntimeDyldELF.cpp \
	RuntimeDyldMachO.cpp

.include "../clang.lib.mk"
