# $FreeBSD: head/lib/clang/libllvmruntimedyld/Makefile 280031 2015-03-15 13:31:13Z dim $

.include <bsd.own.mk>

LIB=	llvmruntimedyld

SRCDIR=	lib/ExecutionEngine/RuntimeDyld
SRCS=	RTDyldMemoryManager.cpp \
	RuntimeDyld.cpp \
	RuntimeDyldChecker.cpp \
	RuntimeDyldELF.cpp \
	RuntimeDyldMachO.cpp

.include "../clang.lib.mk"
