# $FreeBSD: head/usr.sbin/services_mkdb/Makefile 275054 2014-11-25 16:57:27Z bapt $

PROG=	services_mkdb
MAN=	services_mkdb.8
SRCS=	services_mkdb.c uniq.c extern.h

LIBADD=	util

.include <bsd.prog.mk>
