# $FreeBSD: head/usr.bin/clang/llvm-nm/Makefile 261991 2014-02-16 19:44:07Z dim $

.include <bsd.own.mk>

PROG_CXX=llvm-nm

SRCDIR=	tools/llvm-nm
SRCS=	llvm-nm.cpp

LIBDEPS=llvmobject \
	llvmbitreader \
	llvmcore \
	llvmsupport

.include "../clang.prog.mk"
