#	@(#)Makefile	8.1 (Berkeley) 6/8/93
# $FreeBSD: head/share/skel/Makefile 284255 2015-06-11 04:22:17Z sjg $

FILESGROUPS=	FILES1 FILES2
FILES1=		dot.cshrc dot.login dot.login_conf dot.mailrc dot.profile \
		dot.shrc
FILES2=		dot.mail_aliases dot.rhosts 
FILES1DIR=	/usr/share/skel
FILES2DIR=	/usr/share/skel
FILES1MODE=	0644
FILES2MODE=	0600

.include <bsd.prog.mk>
