# $FreeBSD: head/sys/modules/am335x_dmtpps/Makefile 286915 2015-08-19 02:37:30Z ian $

.PATH: ${.CURDIR}/../../arm/ti/am335x

KMOD=	am335x_dmtpps
SRCS=	am335x_dmtpps.c

SRCS+= bus_if.h device_if.h ofw_bus_if.h

.include <bsd.kmod.mk>
