# $FreeBSD: head/gnu/usr.bin/groff/src/preproc/html/Makefile 267233 2014-06-08 17:29:31Z bdrewery $

PROG_CXX=	pre-grohtml
SRCS=		pre-html.cpp pushback.cpp
DPADD=		${LIBGROFF}
LDADD=		${LIBGROFF}
MAN=

NO_PIE=	yes

.include <bsd.prog.mk>
