# $FreeBSD: head/lib/clang/libllvmtarget/Makefile 280031 2015-03-15 13:31:13Z dim $

.include <bsd.own.mk>

LIB=	llvmtarget

SRCDIR=	lib/Target
SRCS=	Target.cpp \
	TargetIntrinsicInfo.cpp \
	TargetLibraryInfo.cpp \
	TargetLoweringObjectFile.cpp \
	TargetMachine.cpp \
	TargetMachineC.cpp \
	TargetSubtargetInfo.cpp

.include "../clang.lib.mk"
