# $FreeBSD: head/lib/clang/libllvmmirparser/Makefile 296417 2016-03-05 20:24:31Z dim $

.include <bsd.own.mk>

LIB=	llvmmirparser

SRCDIR=	lib/CodeGen/MIRParser
SRCS=	MILexer.cpp \
	MIParser.cpp \
	MIRParser.cpp

TGHDRS=	Attributes

.include "../clang.lib.mk"
