# $FreeBSD: head/lib/clang/libllvmdebuginfodwarf/Makefile 283770 2015-05-30 15:39:49Z dim $

.include <src.opts.mk>

LIB=	llvmdebuginfodwarf

SRCDIR=	lib/DebugInfo/DWARF
SRCS=	DWARFAbbreviationDeclaration.cpp \
	DWARFAcceleratorTable.cpp \
	DWARFCompileUnit.cpp \
	DWARFContext.cpp \
	DWARFDebugAbbrev.cpp \
	DWARFDebugArangeSet.cpp \
	DWARFDebugAranges.cpp \
	DWARFDebugFrame.cpp \
	DWARFDebugInfoEntry.cpp \
	DWARFDebugLine.cpp \
	DWARFDebugLoc.cpp \
	DWARFDebugRangeList.cpp \
	DWARFFormValue.cpp \
	DWARFTypeUnit.cpp \
	DWARFUnit.cpp \
	SyntaxHighlighting.cpp

.include "../clang.lib.mk"
