# $FreeBSD: head/libexec/atf/atf-check/tests/Makefile 263161 2014-03-14 08:56:19Z jmmv $

.include <bsd.init.mk>

TESTSDIR=	${TESTSBASE}/libexec/atf/atf-check

ATF=		${.CURDIR:H:H:H:H}/contrib/atf
.PATH:		${ATF}/atf-sh

ATF_TESTS_SH=	atf-check_test

.include <bsd.test.mk>
