# $FreeBSD: head/libexec/atf/atf-check/tests/Makefile 289172 2015-10-12 08:16:03Z ngie $

.include <bsd.init.mk>

ATF=		${SRCTOP}/contrib/atf
.PATH:		${ATF}/atf-sh

ATF_TESTS_SH=	atf-check_test

.include <bsd.test.mk>
