#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: head/usr.bin/tput/Makefile 268804 2014-07-17 18:24:34Z brooks $

PROG=	tput
DPADD=	${LIBTERMCAPW}
LDADD=	-ltermcapw
SCRIPTS=clear.sh
MLINKS=	tput.1 clear.1

.include <bsd.prog.mk>
