# $FreeBSD: head/usr.sbin/bsdconfig/ttys/Makefile 274073 2014-11-04 00:14:38Z dteske $

NO_OBJ=

SUBDIR= include

FILESDIR=	${LIBEXECDIR}/bsdconfig/150.ttys
FILES=		INDEX USAGE

SCRIPTSDIR=	${FILESDIR}
SCRIPTS=	ttys

.include <bsd.prog.mk>
