# $FreeBSD: head/tools/tools/net80211/stumbler/Makefile 268804 2014-07-17 18:24:34Z brooks $

PROG=	stumbler
BINDIR=	/usr/local/bin
DPADD=	${LIBPCAP} ${LIBNCURSESW}
LDADD=	-lpcap -lncursesw
CFLAGS=-g
MAN=

.include <bsd.prog.mk>
