# $FreeBSD: head/tools/tools/net80211/stumbler/Makefile 264400 2014-04-13 05:21:56Z imp $

PROG=	stumbler
BINDIR=	/usr/local/bin
DPADD=	${LIBPCAP} ${LIBNCURSES}
LDADD=	-lpcap -lncurses
CFLAGS=-g
MAN=

.include <bsd.prog.mk>
