# $FreeBSD: head/gnu/usr.bin/groff/src/utils/tfmtodit/Makefile 270168 2014-08-19 15:04:32Z bdrewery $

PROG_CXX=	tfmtodit
SRCS=		tfmtodit.cpp
DPADD=		${LIBGROFF} ${LIBM}
LDADD=		${LIBGROFF} -lm
CLEANFILES=	${MAN}

.include <bsd.prog.mk>
