# $FreeBSD: head/usr.sbin/ctm/ctm_smail/Makefile 264400 2014-04-13 05:21:56Z imp $

.PATH: ${.CURDIR}/../ctm_rmail

PROG=	ctm_smail
MAN=
SRCS=	ctm_smail.c error.c

CFLAGS+= -I${.CURDIR}/../ctm_rmail

WARNS?=	2

.include <bsd.prog.mk>
