# $FreeBSD: head/usr.sbin/bsdinstall/distfetch/Makefile 275054 2014-11-25 16:57:27Z bapt $

BINDIR= /usr/libexec/bsdinstall
PROG=	distfetch
LIBADD=	fetch ncursesw dialog m

WARNS?=	6
MAN=

.include <bsd.prog.mk>
