# $FreeBSD: head/sys/modules/linprocfs/Makefile 283421 2015-05-24 15:51:18Z dchagin $

.PATH: ${.CURDIR}/../../compat/linprocfs

KMOD=	linprocfs
SRCS=	vnode_if.h \
	device_if.h bus_if.h \
	linprocfs.c

.include <bsd.kmod.mk>
