# $FreeBSD: head/lib/clang/liblldbInitialization/Makefile 285116 2015-07-04 01:02:43Z emaste $

.include <bsd.own.mk>

LIB=	lldbInitialization

SRCDIR=	tools/lldb/source/Initialization
SRCS=	SystemInitializer.cpp \
	SystemInitializerCommon.cpp \
	SystemLifetimeManager.cpp
	
#TGHDRS=	AttrList \
#	Attrs \
#	DiagnosticCommonKinds \
#	DeclNodes \
#	StmtNodes \
#	CommentCommandList

.include "../lldb.lib.mk"
