# $FreeBSD: head/lib/libiconv_modules/UTF1632/Makefile 260334 2014-01-05 21:03:49Z dim $

SHLIB=	UTF1632
SRCS+=	citrus_utf1632.c
CFLAGS.gcc+= --param max-inline-insns-single=32

.include <bsd.lib.mk>
