# ex:ts=8
#
# Makefile for amd
# 	This file is under a "BSD" copyright (c) by David O'Brien 1998
#
# $FreeBSD: head/usr.sbin/amd/mk-amd-map/Makefile 267233 2014-06-08 17:29:31Z bdrewery $

.PATH: ${.CURDIR}/../../../contrib/amd/mk-amd-map

PROG=	mk-amd-map
MAN=	mk-amd-map.8

DPADD=	${LIBAMU}
LDADD=	${LIBAMU}

NO_PIE=	yes

.include <bsd.prog.mk>
