#	$FreeBSD: head/sbin/ipf/Makefile 288249 2015-09-26 01:28:50Z bdrewery $

SUBDIR=		libipf .WAIT
SUBDIR+=	ipf ipfs ipfstat ipftest ipmon ipnat ippool ipresend
SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
