# $FreeBSD: head/sys/modules/if_gre/Makefile 269540 2014-08-04 22:37:02Z imp $

.PATH: ${.CURDIR}/../../net ${.CURDIR}/../../netinet ${.CURDIR}/../../netinet6

KMOD=	if_gre
SRCS=	if_gre.c ip_gre.c opt_inet.h opt_inet6.h

.include <bsd.kmod.mk>
