# $FreeBSD: head/lib/clang/libllvmtablegen/Makefile 288943 2015-10-06 17:53:29Z dim $

.include <bsd.own.mk>

LIB=	llvmtablegen

SRCDIR=	lib/TableGen
SRCS=	Error.cpp \
	Main.cpp \
	Record.cpp \
	SetTheory.cpp \
	StringMatcher.cpp \
	TGLexer.cpp \
	TGParser.cpp \
	TableGenBackend.cpp

.include "../clang.lib.mk"
