# $FreeBSD: head/lib/clang/liblldbPluginInstructionMIPS/Makefile 285116 2015-07-04 01:02:43Z emaste $

.include <bsd.own.mk>

LIB=	lldbPluginInstructionMIPS

SRCDIR=	tools/lldb/source/Plugins/Instruction/MIPS
SRCS=	EmulateInstructionMIPS.cpp

TGHDRS=	DiagnosticCommonKinds \
	DeclNodes \
	StmtNodes \
	CommentCommandList

.include "../lldb.lib.mk"
