# $FreeBSD: head/share/doc/papers/Makefile 282219 2015-04-29 13:30:04Z bapt $

SUBDIR=	beyond4.3 \
	bufbio \
	contents \
	devfs \
	diskperf \
	fsinterface \
	jail \
	kernmalloc \
	kerntune \
	malloc \
	newvm \
	relengr \
	sysperf \
	timecounter

.include <bsd.subdir.mk>
