# $FreeBSD: head/share/doc/legal/realtek/Makefile 284321 2015-06-12 14:30:27Z sjg $

FILES=		${.CURDIR}/../../../../sys/contrib/dev/urtwn/LICENSE
FILESDIR=	${SHAREDIR}/doc/legal/realtek

.include <bsd.prog.mk>
