# $FreeBSD: head/usr.sbin/sa/tests/Makefile 299094 2016-05-04 23:20:53Z ngie $

PACKAGE=	tests

TAP_TESTS_SH=	legacy_test

${PACKAGE}FILES+=		v1-amd64-sav.in
${PACKAGE}FILES+=		v1-amd64-sav.out
${PACKAGE}FILES+=		v1-amd64-u.out
${PACKAGE}FILES+=		v1-amd64-usr.in
${PACKAGE}FILES+=		v1-amd64-usr.out
${PACKAGE}FILES+=		v1-i386-sav.in
${PACKAGE}FILES+=		v1-i386-sav.out
${PACKAGE}FILES+=		v1-i386-u.out
${PACKAGE}FILES+=		v1-i386-usr.in
${PACKAGE}FILES+=		v1-i386-usr.out
${PACKAGE}FILES+=		v1-sparc64-sav.in
${PACKAGE}FILES+=		v1-sparc64-sav.out
${PACKAGE}FILES+=		v1-sparc64-u.out
${PACKAGE}FILES+=		v1-sparc64-usr.in
${PACKAGE}FILES+=		v1-sparc64-usr.out
${PACKAGE}FILES+=		v2-amd64-sav.in
${PACKAGE}FILES+=		v2-amd64-u.out
${PACKAGE}FILES+=		v2-amd64-usr.in
${PACKAGE}FILES+=		v2-i386-sav.in
${PACKAGE}FILES+=		v2-i386-u.out
${PACKAGE}FILES+=		v2-i386-usr.in
${PACKAGE}FILES+=		v2-sparc64-sav.in
${PACKAGE}FILES+=		v2-sparc64-u.out
${PACKAGE}FILES+=		v2-sparc64-usr.in

.include <bsd.test.mk>
